#!/bin/zsh
submission=$1
java_path="/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java"
alloy_jar="${PWD}/Alloy/Alloy-5.0.0.1.jar"
alloy_par="edu.mit.csail.sdg.alloy4whole.ExampleUsingTheCompiler"
student_dir=${submission%%_*}
echo $student_dir

mkdir -p $student_dir


# ===== Task 1.1. ===== #
# ===== Task 1.1. send ===== #
echo ""
echo "************************* Marking Task 1.1 send require 0 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
cp "${PWD}/helpers/scaffold1.1.1.als" "$student_dir/task1.1.1.als"
echo "\n" >> "$student_dir/task1.1.1.als"
awk '/pred user_send_post/, /}/' $submission >> "$student_dir/task1.1.1.als"
echo "\n" >> "$student_dir/task1.1.1.als"
cat "${PWD}/helpers/task1_1_1_helper.als" >> "$student_dir/task1.1.1.als"
$java_path -cp $alloy_jar $alloy_par "$student_dir/task1.1.1.als" 2>&1 | grep  --line-buffered "Check\|INSTANCE\|Unsatisfiable\|Exception\|cannot be found" | awk '{gsub(/INSTANCE|Unsatisfiable|Exception|cannot be found/, "\033[31;1;4m&\033[0m");print }' || true

# ===== Task 1.1. recv ===== #
echo ""
echo "************************* Marking Task 1.1 recv require 0 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
cp "${PWD}/helpers/scaffold1.1.2.als" "$student_dir/task1.1.2.als"
echo "\n" >> "$student_dir/task1.1.2.als"
awk '/pred user_recv_post/, /}/' $submission >> "$student_dir/task1.1.2.als"
echo "\n" >> "$student_dir/task1.1.2.als"
cat "${PWD}/helpers/task1_1_2_helper.als" >> "$student_dir/task1.1.2.als"
$java_path -cp $alloy_jar $alloy_par "$student_dir/task1.1.2.als" 2>&1 |  grep  --line-buffered "Check\|INSTANCE\|Unsatisfiable\|Exception\|cannot be found" | awk '{gsub(/INSTANCE|Unsatisfiable|Exception|cannot be found/, "\033[31;1;4m&\033[0m");print }' || true


# ===== Task 1.2. ===== #
echo ""
echo "************************* Marking Task 1.2 require 0 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
cp "${PWD}/helpers/scaffold.als" "$student_dir/task1.2.0.als"
echo "\n" >> "$student_dir/task1.2.0.als"
awk '/pred user_recv_post/, /}/' $submission >> "$student_dir/task1.2.0.als"
echo "\n" >> "$student_dir/task1.2.0.als"
awk '/pred user_send_post/, /}/' $submission >> "$student_dir/task1.2.0.als"
echo "\n" >> "$student_dir/task1.2.0.als"
awk '/assert no_bad_states/, /}/' $submission >> "$student_dir/task1.2.0.als"
cat "${PWD}/helpers/fact_1_2_0.als" >> "$student_dir/task1.2.0.als"
$java_path -cp $alloy_jar $alloy_par "$student_dir/task1.2.0.als" 2>&1 | grep  --line-buffered "Check\|INSTANCE\|Unsatisfiable\|Exception\|cannot be found" | awk '{gsub(/INSTANCE|Unsatisfiable|Exception|cannot be found/, "\033[31;1;4m&\033[0m");print }' || true

echo ""
echo "************************* Marking Task 1.2 require 1 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
cp "${PWD}/helpers/scaffold.als" "$student_dir/task1.2.1.als"
echo "\n" >> "$student_dir/task1.2.1.als"
awk '/pred user_recv_post/, /}/' $submission >> "$student_dir/task1.2.1.als"
echo "\n" >> "$student_dir/task1.2.1.als"
awk '/pred user_send_post/, /}/' $submission >> "$student_dir/task1.2.1.als"
awk '/assert no_bad_states/, /}/' $submission >> "$student_dir/task1.2.1.als"
cat "${PWD}/helpers/fact_1_2_1.als" >> "$student_dir/task1.2.1.als"
$java_path -cp $alloy_jar $alloy_par "$student_dir/task1.2.1.als" 2>&1 | grep  --line-buffered "Check\|INSTANCE\|Unsatisfiable\|Exception\|cannot be found" | awk '{gsub(/INSTANCE|Unsatisfiable|Exception|cannot be found/, "\033[31;1;4m&\033[0m");print }' || true


echo ""
echo "************************* Marking Task 1.3 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
awk '/\/\/ .* vulnerability/, /^[^\/]/' $submission | awk '{gsub(/[cC]aller|[cC]allee|Connect|SignallingComplete/, "\033[31;1;4m&\033[0m");print }'


# ===== Task 2.1. ===== #
echo ""
echo "************************* Marking Task 2.1 require 0 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
cp "$submission" "$student_dir/task2.1.als"
sed -i "" '/^run/d' "$student_dir/task2.1.als"
sed -i "" '/^check/d' "$student_dir/task2.1.als"
echo "check no_bad_states for 8 but 3 Address" >> "$student_dir/task2.1.als"
$java_path -cp $alloy_jar $alloy_par "$student_dir/task2.1.als" 2>&1 | grep  --line-buffered "Check\|INSTANCE\|Unsatisfiable\|Exception\|cannot be found" | awk '{gsub(/INSTANCE|Unsatisfiable|Exception|cannot be found/, "\033[31;1;4m&\033[0m");print }' || true


# ===== Task 2.1. ===== #
echo ""
echo "************************* Marking Task 2.2 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
grep "check no_bad_states for" $submission | awk '{gsub(/[0-9]/, "\033[31;1;4m&\033[0m");print }'


# ===== Task 2.3.1. ===== #
echo ""
echo "************************* Marking Task 2.3.1 require 0 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
awk '/^run/, /$/' $submission | awk '{gsub(/[0-9]|run/, "\033[31;1;4m&\033[0m");print }'
echo ""
cp "$submission" "$student_dir/task2.3.1.0.als"
sed -i "" '/^check/d' "$student_dir/task2.3.1.0.als"
cat "helpers/fact_2_3_1_0.als" >> "$student_dir/task2.3.1.0.als"
$java_path -cp $alloy_jar $alloy_par "$student_dir/task2.3.1.0.als" 2>&1 | grep --line-buffered "Run\|INSTANCE\|Unsatisfiable\|Exception\|cannot be found" | awk '{gsub(/INSTANCE|Unsatisfiable|Exception|cannot be found|Default/, "\033[31;1;4m&\033[0m");print }' || true

echo ""
echo "************************* Marking Task 2.3.1 require 1 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
cp "$submission" "$student_dir/task2.3.1.1.als"
sed -i "" '/^check/d' "$student_dir/task2.3.1.1.als"
$java_path -cp $alloy_jar $alloy_par "$student_dir/task2.3.1.1.als" 2>&1 | grep --line-buffered "Run\|INSTANCE\|Unsatisfiable\|Exception\|cannot be found" | awk '{gsub(/INSTANCE|Unsatisfiable|Exception|cannot be found|Default/, "\033[31;1;4m&\033[0m");print }' || true


# ===== Task 2.3.2. ===== #
echo ""
echo "************************* Marking Task 2.3.2 require 0 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
cp "$submission" "$student_dir/task2.3.2.0.als"
sed -i "" '/^check/d' "$student_dir/task2.3.2.0.als"
cat "helpers/fact_2_3_2_0.als" >> "$student_dir/task2.3.2.0.als"
$java_path -cp $alloy_jar $alloy_par "$student_dir/task2.3.2.0.als" 2>&1 | grep --line-buffered "Run\|INSTANCE\|Unsatisfiable\|Exception\|cannot be found" | awk '{gsub(/INSTANCE|Unsatisfiable|Exception|cannot be found|Default/, "\033[31;1;4m&\033[0m");print }' || true

echo ""
echo "************************* Marking Task 2.3.2 require 1 ************************* " | awk '{gsub(/[0-9\.]/, "\033[31;1;4m&\033[0m"); print}'
cp "$submission" "$student_dir/task2.3.2.1.als"
sed -i "" '/^check/d' "$student_dir/task2.3.2.1.als"
cat "helpers/fact_2_3_2_1.als" >> "$student_dir/task2.3.2.1.als"
$java_path -cp $alloy_jar $alloy_par "$student_dir/task2.3.2.1.als" 2>&1 | grep --line-buffered "Run\|INSTANCE\|Unsatisfiable\|Exception\|cannot be found" | awk '{gsub(/INSTANCE|Unsatisfiable|Exception|cannot be found|Default/, "\033[31;1;4m&\033[0m");print }' || true

echo ""
echo "************************* All Done ************************* " | awk '{gsub(/All Done/, "\033[31;1;4m&\033[0m"); print}'
